schematicPath: "JumpAndRunIsland.schem"

debug: true

# JumpAndRun-DB (besteht schon bei dir)
mysql:
  host: localhost
  port: 3306
  database: jnr
  user: root
  password: geheim

# Punkte-DB f√ºr RankPointsAPI (separat!)
pointsdb:
  host: localhost
  port: 3306
  database: rankpoints
  user: rankuser
  password: anderespasswort
  excludeStaff: true

plates:
  start: HEAVY_WEIGHTED_PRESSURE_PLATE
  end: LIGHT_WEIGHTED_PRESSURE_PLATE
  checkpoint: STONE_PRESSURE_PLATE

points:
  new-record: 10